# Header
menu:
  主页: /
  所有文章: /archives
  # 我的影集: /instagram
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: https://github.com/dannywj
  weibo: http://weibo.com/wudixiaojue
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: https://raw.githubusercontent.com/dannywj/DannyWebSite/master/DannyWebSite/images/face.jpg
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  旋转木马的博客: http://blog.sina.com.cn/dannywj1371
  我的博客园: http://www.cnblogs.com/dannywang/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 人生就是一场旅行，不在乎目的地，在乎的应该是沿途的风景以及看风景的心情。      摄影就是一种形式，不在乎照片的华丽，在乎的是按下快门时对灵魂的触动以及美好过往的留恋
